# Generated by Django 6.0.4 on 2026-04-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesforce_id', models.CharField(max_length=255, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_id', models.CharField(max_length=100)),
                ('application_status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('conditional_offer', 'Conditional Offer'), ('unconditional_offer', 'Unconditional Offer'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected')], default='submitted', max_length=50)),
                ('course_name', models.CharField(max_length=255)),
                ('intake_year', models.IntegerField()),
                ('intake_semester', models.CharField(max_length=50)),
                ('offer_details', models.TextField(blank=True, null=True)),
                ('offer_deadline', models.DateField(blank=True, null=True)),
                ('documents_verified', models.BooleanField(default=False)),
                ('missing_documents', models.TextField(blank=True, null=True)),
                ('last_communication', models.TextField(blank=True, null=True)),
                ('admission_officer_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Student Application',
                'verbose_name_plural': 'Student Applications',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=20)),
                ('records_synced', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-synced_at'],
            },
        ),
    ]
